image:
  jfy133/quarto-plus-r

  # List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: quarto
    init: |
      quarto install tinytex --no-prompt
    command: quarto preview /workspace/intro-to-ancient-metagenomics-book --render all --no-browser --no-watch-inputs

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - quarto.quarto
    - REditorSupport.r
    - streetsidesoftware.code-spell-checker
